#!/command/with-contenv bash
# shellcheck shell=bash

# Description:
# This script is executed by the s6 supervisor when the container starts.
# It sets the file creation mask to the value of UMASK, which determines the default permissions for newly created files.
# It also displays the application banner and environment variables with some masked for security.

# Set the file creation mask to the value of UMASK, which determines the default permissions for newly created files.
umask "${UMASK}"

# Function to mask sensitive information by replacing characters with asterisks, leaving the last few characters visible.
mask() {
    local n=3
    # If the length of the input string is less than or equal to 5, adjust the number of visible characters accordingly.
    [[ ${#1} -le 5 ]] && n=$(( ${#1} - 3 ))
    local a="${1:0:${#1}-n}"
    local b="${1:${#1}-n}"
    printf "%s%s\n" "${a//?/*}" "$b"
}

# Display application banner and environment variables with some masked for security.
echo "
$(figlet -d /usr/share/figlet -f Cyberlarge.flf "lidarr")
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
----------------------------------------------------------------------
"
